import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "de" | "ru";

interface Translations {
  nav: {
    home: string;
    generate: string;
    avatars: string;
    repository: string;
    history: string;
    login: string;
    logout: string;
  };
  hero: {
    tagline: string;
    subtitle: string;
    cta: string;
    ctaSecondary: string;
  };
  avatars: {
    berlin: { name: string; title: string; bio: string; specialty: string };
    moscow: { name: string; title: string; bio: string; specialty: string };
    london: { name: string; title: string; bio: string; specialty: string };
  };
  generate: {
    title: string;
    placeholder: string;
    submit: string;
    formats: {
      text: string;
      scientific: string;
      poster: string;
      creative: string;
      song: string;
    };
    generating: string;
    newSession: string;
    download: string;
    share: string;
    imageToggle: string;
  };
  repository: {
    title: string;
    subtitle: string;
    empty: string;
  };
  history: {
    title: string;
    empty: string;
    deleteConfirm: string;
  };
  common: {
    loading: string;
    error: string;
    save: string;
    cancel: string;
    delete: string;
    public: string;
    private: string;
  };
}

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      home: "Home",
      generate: "Generate",
      avatars: "Avatars",
      repository: "Repository",
      history: "History",
      login: "Sign In",
      logout: "Sign Out",
    },
    hero: {
      tagline: "Transcend Knowledge. Across Languages. Across Worlds.",
      subtitle: "Prize2Pride is the world's first trilingual AI knowledge engine — generating unlimited scientific, creative, and cultural knowledge simultaneously in English, German, and Russian.",
      cta: "Begin Generating",
      ctaSecondary: "Explore Repository",
    },
    avatars: {
      berlin: {
        name: "BERLIN",
        title: "The Architect of Reason",
        bio: "Born from the intellectual crucible of Berlin — where Hegel, Einstein, and Brecht once walked. The Berlin Avatar embodies rigorous scientific thought, philosophical depth, and the relentless pursuit of structured knowledge.",
        specialty: "Science · Philosophy · Engineering",
      },
      moscow: {
        name: "MOSCOW",
        title: "The Keeper of Fire",
        bio: "Forged in the heart of Moscow — where Tolstoy, Mendeleev, and Tchaikovsky shaped civilization. The Moscow Avatar channels the raw power of Russian intellectual tradition: vast, passionate, and boundless.",
        specialty: "Literature · Mathematics · Arts",
      },
      london: {
        name: "LONDON",
        title: "The Bridge Between Worlds",
        bio: "Shaped by London — the crossroads of empire, innovation, and renaissance. The London Avatar synthesizes global knowledge streams, bridging East and West, past and future, science and soul.",
        specialty: "Innovation · Culture · Synthesis",
      },
    },
    generate: {
      title: "Knowledge Generation Engine",
      placeholder: "Enter any topic, question, or concept — receive unlimited knowledge in three languages simultaneously...",
      submit: "Generate Knowledge",
      formats: {
        text: "Long-Form Text",
        scientific: "Scientific Paper",
        poster: "Knowledge Poster",
        creative: "Creative Work",
        song: "Song / Lyrics",
      },
      generating: "Generating trilingual knowledge...",
      newSession: "New Session",
      download: "Download",
      share: "Share",
      imageToggle: "Generate Visual",
    },
    repository: {
      title: "Public Knowledge Repository",
      subtitle: "A living archive of knowledge generated by the Prize2Pride community — open, searchable, and growing.",
      empty: "No public knowledge entries yet. Be the first to contribute.",
    },
    history: {
      title: "Knowledge History",
      empty: "No sessions yet. Start generating knowledge to build your archive.",
      deleteConfirm: "Delete this session permanently?",
    },
    common: {
      loading: "Loading...",
      error: "An error occurred. Please try again.",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      public: "Public",
      private: "Private",
    },
  },

  de: {
    nav: {
      home: "Startseite",
      generate: "Generieren",
      avatars: "Avatare",
      repository: "Repository",
      history: "Verlauf",
      login: "Anmelden",
      logout: "Abmelden",
    },
    hero: {
      tagline: "Wissen transzendieren. Über Sprachen. Über Welten.",
      subtitle: "Prize2Pride ist die weltweit erste dreisprachige KI-Wissensmaschine — sie generiert unbegrenztes wissenschaftliches, kreatives und kulturelles Wissen gleichzeitig auf Englisch, Deutsch und Russisch.",
      cta: "Jetzt Generieren",
      ctaSecondary: "Repository Erkunden",
    },
    avatars: {
      berlin: {
        name: "BERLIN",
        title: "Der Architekt der Vernunft",
        bio: "Geboren im intellektuellen Schmelztiegel Berlins — wo Hegel, Einstein und Brecht einst wandelten. Der Berlin-Avatar verkörpert rigoroses wissenschaftliches Denken, philosophische Tiefe und das unablässige Streben nach strukturiertem Wissen.",
        specialty: "Wissenschaft · Philosophie · Ingenieurwesen",
      },
      moscow: {
        name: "MOSKAU",
        title: "Der Hüter des Feuers",
        bio: "Im Herzen Moskaus geschmiedet — wo Tolstoi, Mendelejew und Tschaikowski die Zivilisation prägten. Der Moskau-Avatar kanalisiert die rohe Kraft der russischen Intellektualtradition: gewaltig, leidenschaftlich und grenzenlos.",
        specialty: "Literatur · Mathematik · Künste",
      },
      london: {
        name: "LONDON",
        title: "Die Brücke zwischen Welten",
        bio: "Geformt durch London — den Kreuzweg von Imperium, Innovation und Renaissance. Der London-Avatar synthetisiert globale Wissensströme und verbindet Ost und West, Vergangenheit und Zukunft, Wissenschaft und Seele.",
        specialty: "Innovation · Kultur · Synthese",
      },
    },
    generate: {
      title: "Wissensgenerierungs-Engine",
      placeholder: "Geben Sie ein Thema, eine Frage oder ein Konzept ein — erhalten Sie unbegrenztes Wissen in drei Sprachen gleichzeitig...",
      submit: "Wissen Generieren",
      formats: {
        text: "Langtext",
        scientific: "Wissenschaftliche Arbeit",
        poster: "Wissens-Poster",
        creative: "Kreatives Werk",
        song: "Lied / Lyrics",
      },
      generating: "Dreisprachiges Wissen wird generiert...",
      newSession: "Neue Sitzung",
      download: "Herunterladen",
      share: "Teilen",
      imageToggle: "Visuell Generieren",
    },
    repository: {
      title: "Öffentliches Wissens-Repository",
      subtitle: "Ein lebendiges Archiv des von der Prize2Pride-Community generierten Wissens — offen, durchsuchbar und wachsend.",
      empty: "Noch keine öffentlichen Wissenseinträge. Sei der Erste, der einen Beitrag leistet.",
    },
    history: {
      title: "Wissensverlauf",
      empty: "Noch keine Sitzungen. Beginnen Sie mit der Generierung von Wissen, um Ihr Archiv aufzubauen.",
      deleteConfirm: "Diese Sitzung dauerhaft löschen?",
    },
    common: {
      loading: "Laden...",
      error: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
      save: "Speichern",
      cancel: "Abbrechen",
      delete: "Löschen",
      public: "Öffentlich",
      private: "Privat",
    },
  },

  ru: {
    nav: {
      home: "Главная",
      generate: "Генерация",
      avatars: "Аватары",
      repository: "Репозиторий",
      history: "История",
      login: "Войти",
      logout: "Выйти",
    },
    hero: {
      tagline: "Превзойди знание. Через языки. Через миры.",
      subtitle: "Prize2Pride — первый в мире трёхъязычный движок знаний на основе ИИ, генерирующий неограниченные научные, творческие и культурные знания одновременно на английском, немецком и русском языках.",
      cta: "Начать Генерацию",
      ctaSecondary: "Исследовать Репозиторий",
    },
    avatars: {
      berlin: {
        name: "БЕРЛИН",
        title: "Архитектор Разума",
        bio: "Рождённый в интеллектуальном горниле Берлина — где некогда ходили Гегель, Эйнштейн и Брехт. Берлинский Аватар воплощает строгое научное мышление, философскую глубину и неустанное стремление к структурированному знанию.",
        specialty: "Наука · Философия · Инженерия",
      },
      moscow: {
        name: "МОСКВА",
        title: "Хранитель Огня",
        bio: "Выкованный в сердце Москвы — где Толстой, Менделеев и Чайковский формировали цивилизацию. Московский Аватар воплощает необузданную мощь русской интеллектуальной традиции: необъятной, страстной и безграничной.",
        specialty: "Литература · Математика · Искусства",
      },
      london: {
        name: "ЛОНДОН",
        title: "Мост Между Мирами",
        bio: "Сформированный Лондоном — перекрёстком империи, инноваций и Ренессанса. Лондонский Аватар синтезирует глобальные потоки знаний, соединяя Восток и Запад, прошлое и будущее, науку и душу.",
        specialty: "Инновации · Культура · Синтез",
      },
    },
    generate: {
      title: "Движок Генерации Знаний",
      placeholder: "Введите любую тему, вопрос или концепцию — получите неограниченные знания на трёх языках одновременно...",
      submit: "Генерировать Знания",
      formats: {
        text: "Длинный Текст",
        scientific: "Научная Статья",
        poster: "Постер Знаний",
        creative: "Творческое Произведение",
        song: "Песня / Текст",
      },
      generating: "Генерация трёхъязычных знаний...",
      newSession: "Новая Сессия",
      download: "Скачать",
      share: "Поделиться",
      imageToggle: "Создать Визуал",
    },
    repository: {
      title: "Публичный Репозиторий Знаний",
      subtitle: "Живой архив знаний, созданных сообществом Prize2Pride — открытый, доступный для поиска и постоянно растущий.",
      empty: "Публичных записей знаний пока нет. Будьте первым, кто внесёт вклад.",
    },
    history: {
      title: "История Знаний",
      empty: "Сессий пока нет. Начните генерировать знания, чтобы создать свой архив.",
      deleteConfirm: "Удалить эту сессию навсегда?",
    },
    common: {
      loading: "Загрузка...",
      error: "Произошла ошибка. Пожалуйста, попробуйте снова.",
      save: "Сохранить",
      cancel: "Отмена",
      delete: "Удалить",
      public: "Публичный",
      private: "Приватный",
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const t = translations[language];
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
